### ISSUE TITLE
BrnoCompSpeed dataset request

### ISSUE THREAD

**Issue by IncrediBlame** [IncrediBlame/BrnoCompSpeed_recovery#1]
@JakubSochor @JakubSpanhel @shridharkini6 @shridharkini @gentle1212 @chandu0211 @danlapko @Nuzhny007 @keeprunningcelin @molua @AnilKumar75 @meher-chinmaya @hanlanqian @wsz1998 @tuqingyun @hashshura @ghost @darkdurumi 

Hi folks, sorry for spamming.

Given [BrnoCompSpeed](https://github.com/JakubSochor/BrnoCompSpeed) downloading is not possible anymore. Does anyone still have access to the dataset and can share it? We can use croc or whatnot.

I am doing a related research and there seems like no equivalent dataset exists in the wild. I promise to keep it and provide access as long as I can.

Respond here or by email (incrediblame@gmail.com) if you can help.

**Comment by Nuzhny007** [comment]
Hi!
You can download a parted archive (about 27 Gb):
https://cloud.mail.ru/public/okrS/2YNMqp72Z

**Comment by IncrediBlame** [comment]
Hi,

Thank you so much!

**Comment by IncrediBlame** [comment]
Thanks everyone, one of the authors replied, and the issue has been resolved.

For anyone looking to download the dataset, [follow the instructions](https://github.com/JakubSochor/BrnoCompSpeed?tab=readme-ov-file#download) and wait. The authors will eventually reply.
